name: Linux

on:
    push:
        branches: [development, main]
    pull_request:
        branches: [development, main]

jobs:

    linux:
        uses: gilmourspace/workflows/.github/workflows/linux-ci-swift.yml@v1
        secrets: inherit
