name: macOS

on:
    push:
        branches: [development, main]
    pull_request:
        branches: [development, main]

jobs:

    macOS:
        uses: gilmourspace/workflows/.github/workflows/macOS-ci-swift.yml@v1
        secrets: inherit
