name: Coverage

on:
    push:
        branches: [development, main]
    pull_request:
        branches: [development, main]

jobs:

    coverage:
        uses: gilmourspace/workflows/.github/workflows/linux-coverage-swift.yml@v1
        secrets: inherit
