name: Linting

on:
    push:
        branches: [development, main]
    pull_request:
        branches: [development, main]

jobs:

    lint:
        uses: gilmourspace/workflows/.github/workflows/linux-lint-swift.yml@v1
        secrets: inherit
